name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'build-logic/**'
      - 'kotlinc/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'build-logic/**'
      - 'kotlinc/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  workflow_dispatch:

jobs:
  buildlibreMinApi21:
    name: Build libre minApi21 debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upgrading the Wrapper version 
        run: | 
             ./gradlew wrapper --gradle-version 7.5.1 --distribution-type all

      - name: Verify the checksum of the Wrapper JAR
        run: |
             cd gradle/wrapper
             curl --location --output gradle-wrapper.jar.sha256 \
                  https://services.gradle.org/distributions/gradle-7.5.1-wrapper.jar.sha256
             echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
             sha256sum --check gradle-wrapper.jar.sha256

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build libre debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleLibreDebug
        env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

      - name: Upload libre debug APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-libre-debug
          path: app/build/outputs/apk/libre/debug

buildStandardMinApi21:
    name: Build Standard minApi21 debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upgrading the Wrapper version 
        run: | 
             ./gradlew wrapper --gradle-version 7.5.1 --distribution-type all

      - name: Verify the checksum of the Wrapper JAR
        run: |
             cd gradle/wrapper
             curl --location --output gradle-wrapper.jar.sha256 \
                  https://services.gradle.org/distributions/gradle-7.5.1-wrapper.jar.sha256
             echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
             sha256sum --check gradle-wrapper.jar.sha256

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build standard debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemblestandardDebug
        env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

      - name: Upload standard debug APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-standard-debug
          path: app/build/outputs/apk/standard/debug
