name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
workflow_dispatch:
jobs:
  buildlibreMinApi21:
    name: Build libre minApi21 debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build libre debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleLibreDebug
        env:
          CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}

      - name: Upload libre debug APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-libre-debug
          path: app/build/outputs/apk/libre/debug
